export const SKILL_SUGGESTIONS = [
  'Communication',
  'Leadership',
  'Teamwork',
  'Problem Solving',
  'Critical Thinking',
  'Time Management',
  'Project Management',
  'Agile',
  'Scrum',
  'Mentoring',
  'Collaboration',
  'Creativity',
  'Attention to Detail',
  'Adaptability',
  'Organization',
  'Customer Service',
  'Negotiation',
  'Public Speaking',
  'Technical Writing',
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Vue.js',
  'Angular',
  'Svelte',
  'Node.js',
  'HTML',
  'CSS',
  'Tailwind CSS',
  'Python',
  'Go',
  'Java',
  'C#',
  'C++',
  'Rust',
  'Ruby',
  'PHP',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'SQLite',
  'MongoDB',
  'Redis',
  'GraphQL',
  'REST APIs',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'Terraform',
  'Git',
  'CI/CD',
  'Linux',
  'Testing',
  'Jest',
  'Cypress',
  'Data Analysis',
  'Machine Learning',
  'Deep Learning',
  'Data Science',
  'Artificial Intelligence',
  'NLP',
  'Computer Vision',
  'Pandas',
  'NumPy',
  'TensorFlow',
  'PyTorch',
  'DevOps',
  'Security',
  'Cybersecurity',
  'System Design',
  'Distributed Systems',
  'Cloud Architecture',
  'Microservices',
  'Networking',
  'Sales',
  'Marketing',
  'SEO',
  'Content Writing',
  'Product Design',
  'UI/UX Design',
  'Figma',
  'Prototyping',
  'Research',
  'Analytics',
  'Excel',
  'Finance',
  'Accounting',
  'Recruitment',
  'Stakeholder Management',
  'Strategy',
  'Operations'
];

export function getSkillSuggestions(
  query: string,
  exclude: string[] = [],
  limit = 8
): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const excluded = exclude.map((s) => s.trim().toLowerCase());
  return SKILL_SUGGESTIONS.filter((skill) => {
    const norm = skill.toLowerCase();
    return norm.includes(q) && !excluded.includes(norm);
  }).slice(0, limit);
}